export const SET_DATA = 'set_data'
export const SET_CAPITAL_QUESTION = 'set_capital_question'
export const SET_FLAG_QUESTION = 'set_flag_question'
export const SET_IS_SHOW_NEXT_QUESTION = 'set_is_show_next_question'
export const SET_SCORE = 'set_score'
export const SET_IS_PASS = 'set_is_pass'
export const SET_MODE = 'set_mode'